# Enable picoquic-log
option('build_loglib', type : 'boolean', value : false)

# Android NDK root path
option('android_ndk_root', type : 'string', value : '')

# Android API level
option('android_api_level', type : 'string', value : '30')

# Cross-file path
option('cross_file', type : 'string', value : '')

# Android build type
option('android_buildtype', type : 'string', value : 'release')

# Android default library
option('android_default_library', type : 'string', value : 'static')

